stages:
  - checkout
  - fetch_Packages
  - test
  - build
  - package
  - upload

variables:
  NEXUS_CREDENTIALS_ID: 'nexus-jenkins'
  NEXUS_URL: 'https://nexus.u-cloudsolutions.xyz'
  NEXUS_REPOSITORY: 'student-repository'
  GROUP_ID: 'com.artificial.Flutter'
  ARTIFACT_ID: 'project-flutter'
  BRANCH_NAME: "${CI_COMMIT_REF_NAME}"
  BUILD_NUMBER: "${CI_PIPELINE_ID}"

checkout:
  stage: checkout
  tags:
    - flutter
  script:
    - echo "Checking out the repository"
    - git rev-parse --short HEAD > commit_hash.txt
    - export COMMIT_ID=$(cat commit_hash.txt)
    - export ZIP_FILE_NAME="${ARTIFACT_ID}-${COMMIT_ID}.zip"

fetch_Packages:
  stage: fetch_Packages
  tags:
    - docker-flutter
  script:
    - flutter pub get

test:
  stage: test
  tags:
    - docker-flutter
  script:
    - flutter test

build:
  stage: build
  tags:
    - docker-flutter
  script:
    - flutter build apk --release --build-name="${BRANCH_NAME}" --build-number="${BUILD_NUMBER}"

package:
  stage: package
  tags:
    - shell
  script:
    - echo "Cleaning up old ZIP files..."
    - rm -f artifact-*.zip || true
    - echo "Packaging project..."
    - ZIP_FILE_NAME="artifact-${COMMIT_ID}.zip"
    - echo "Packaging project as ${ZIP_FILE_NAME}..."
    - zip -r ${ZIP_FILE_NAME} . || true
    - ls -l ${ZIP_FILE_NAME}
  artifacts:
    paths:
      - artifact-*.zip

upload:
  stage: upload
  tags:
    - shell
  script:
    - echo "Determining commit ID..."
    - ZIP_FILE_NAME="artifact-${COMMIT_ID}.zip"
    - echo "Uploading ${ZIP_FILE_NAME} to Nexus..."
    - UPLOAD_URL="${NEXUS_URL}/repository/${NEXUS_REPOSITORY}/${GROUP_ID//./\/}/${ARTIFACT_ID}/${COMMIT_ID}/${ZIP_FILE_NAME}"
    - pwd  # Print working directory
    - find . -name "*.zip"  # Find ZIP files
    - ls -l ${ZIP_FILE_NAME}  # Verify file existence
    - curl -u ${NEXUS_CREDENTIALS_ID} --upload-file "${ZIP_FILE_NAME}" "${UPLOAD_URL}"




