image: 54.38.185.102:10001/repository/docker-repo/flutter_fastlane_image:latest




stages:
  - fetch_Packages
  - build
  - test 

variables:
  NEXUS_CREDENTIALS_ID: 'nexus-jenkins'
  NEXUS_URL: 'https://nexus.u-cloudsolutions.xyz'
  NEXUS_REPOSITORY: 'student-repository'
  GROUP_ID: 'com.artificial.Flutter'
  ARTIFACT_ID: 'project-flutter'
  CHECKOUT_DIR: 'project-checkout-dir'
  BRANCH_NAME: 'main'
  ZIP_FILE_NAME: '${ARTIFACT_ID}-${COMMIT_ID}.zip'
  COMMIT_ID: $(git rev-parse --short HEAD)
  FLUTTER_HOME: "/opt/flutter"
  ANDROID_SDK_ROOT: "/opt/android-sdk"
  PATH: "$FLUTTER_HOME/bin:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"


before_script:
  # Check Flutter installation and setup project dependencies
  - flutter doctor -v
  - flutter pub get
  - export PATH="$FLUTTER_HOME/bin:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"






fetch_Packages:
  stage: fetch_Packages
  script:
    - flutter pub get



build:
  stage: build
  tags:
    - docker-flutter
  script:
    - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk


test:
  stage: test
  tags:
    - docker-flutter
  script:
    - flutter test
