stages:
  - checkout
  - fetch_Packages
  - test
  - build
  - package
  - upload
  - distribute

variables:
  NEXUS_CREDENTIALS_ID: 'nexus-jenkins'
  NEXUS_URL: 'https://nexus.u-cloudsolutions.xyz'
  NEXUS_REPOSITORY: 'student-repository'
  GROUP_ID: 'com.artificial.Flutter'
  ARTIFACT_ID: 'project-flutter'
  ZIP_FILE_NAME: '${ARTIFACT_ID}-${COMMIT_ID}.zip'

# Définir la variable de branche comme paramètre
  BRANCH_NAME: "${CI_COMMIT_REF_NAME}"

checkout:
  stage: checkout
  tags:
    - flutter
  script:
    - echo "Checking out the repository"
    - git rev-parse --short HEAD > commit_hash.txt
    - export COMMIT_ID=$(cat commit_hash.txt)
    - export ZIP_FILE_NAME="${ARTIFACT_ID}-${COMMIT_ID}.zip"
  rules:
    - if: '$BRANCH_NAME'
      when: always


fetch_Packages:
  stage: fetch_Packages
  tags:
    - docker-flutter
  script:
    - flutter pub get
  rules:
    - if: '$BRANCH_NAME'
      when: always

test:
  stage: test
  tags:
    - docker-flutter
  script:
    - flutter test
  rules:
    - if: '$BRANCH_NAME'
      when: always

build:
  stage: build
  tags:
    - docker-flutter
  script:
    # Définir les variables pour le nom de la branche, le numéro de build et l'ID du commit
    - export BUILD_NUMBER="${CI_PIPELINE_ID}"
    - export COMMIT_ID="${CI_COMMIT_SHORT_SHA}"
    
    # Exécuter la commande de build avec les options --build-name et --build-number
    - flutter build apk --release \
        --build-name="${BRANCH_NAME}" \
        --build-number="${BUILD_NUMBER}"
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
  rules:
    - if: '$BRANCH_NAME'
      when: always

package:
  stage: package
  tags:
    - shell
  script:
    - echo "Cleaning up old ZIP files..."
    - rm -f artifact-*.zip
    - echo "Packaging project..."
    - COMMIT_ID=$(git rev-parse --short HEAD)
    - ZIP_FILE_NAME="artifact-${COMMIT_ID}.zip"
    - echo "Packaging project as ${ZIP_FILE_NAME}..."
    - zip -r ${ZIP_FILE_NAME} .
    - ls -l ${ZIP_FILE_NAME}
  artifacts:
    paths:
      - artifact-*.zip
  rules:
    - if: '$BRANCH_NAME'
      when: always

upload:
  stage: upload
  tags:
    - shell
  script:
    - echo "Determining commit ID..."
    - COMMIT_ID=$(git rev-parse --short HEAD)
    - ZIP_FILE_NAME="artifact-${COMMIT_ID}.zip"
    - echo "Uploading ${ZIP_FILE_NAME} to Nexus..."
    - UPLOAD_URL="${NEXUS_URL}/repository/${NEXUS_REPOSITORY}/${GROUP_ID//./\/}/${ARTIFACT_ID}/${COMMIT_ID}/${ZIP_FILE_NAME}"
    - pwd  # Print working directory
    - find . -name "*.zip"  # Find ZIP files
    - ls -l ${ZIP_FILE_NAME}  # Verify file existence
    - curl -u wissem:3FqNnJ6XzF --upload-file "${ZIP_FILE_NAME}" "${UPLOAD_URL}"
  rules:
    - if: '$BRANCH_NAME'
      when: always

distribute:
  stage: distribute
  tags:
    - docker-flutter
  dependencies:
    - build
  script:
    - apkPath='build/app/outputs/flutter-apk/app-release.apk'
    - tagName="v${CI_PIPELINE_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"
    - echo "APK found at $apkPath. Proceeding with distribution."
    - echo "Distributing APK with tag: $tagName"
    - |
      curl -F "ipa=@${apkPath}" \
           -F "release_notes=Branch: ${CI_COMMIT_REF_NAME} - Build ${CI_PIPELINE_ID} - Commit ${CI_COMMIT_SHORT_SHA}" \
           -F "distribution_group=flutter-app" \
           -H "X-API-Token: 79aabd068b99a4b35b3688e39b1a69ff6eec38e6" \
           https://api.appcenter.ms/v0.1/apps/sghaier-fss.u-sfax.tn/flutter-app/release_uploads
  rules:
    - if: '$BRANCH_NAME'
      when: always

