stages:
  - checkout
  - fetch_Packages

variables:
  NEXUS_CREDENTIALS_ID: 'nexus-jenkins'
  NEXUS_URL: 'https://nexus.u-cloudsolutions.xyz'
  NEXUS_REPOSITORY: 'student-repository'
  GROUP_ID: 'com.artificial.Flutter'
  ARTIFACT_ID: 'project-flutter'
  CHECKOUT_DIR: 'project-checkout-dir'
  BRANCH_NAME: 'main'
  COMMIT_ID: ''
  ZIP_FILE_NAME: ''
  PUB_CACHE: '/home/flutteruser/.pub-cache'

checkout:
  stage: checkout
  tags:
    - shell
  script:
    - echo "Checking out the repository"
    - git rev-parse --short HEAD > commit_hash.txt
    - export COMMIT_ID=$(cat commit_hash.txt)
    - export ZIP_FILE_NAME="${ARTIFACT_ID}-${COMMIT_ID}.zip"



fetch_Packages:
  stage: fetch_Packages
  image: '127.0.1.1:10001/repository/docker-repo/flutter-android-image:latest'
  script:
    - git config --global --add safe.directory /opt/flutter
    - export PUB_CACHE=${PUB_CACHE}
    - flutter --version
    - flutter pub get

