source "https://rubygems.org"

gem "fastlane"
gem "fastlane-plugin-appcenter"

plugins_path = File.join(File.dirname(__FILE__), '.', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
